server:
  port: 12000
spring:
  application:
    name: foodmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.252.128
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
management:
  endpoints:
    web:
      exposure:
        include: '*'