spring:
  datasource:
    username: root
    password: 9780919
    url: jdbc:mysql://localhost:3306/foodmall_ofs?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: foodmall-order

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

  #session存储形式
  session:
    store-type: redis

  redis:
    port: 6379
    host: 192.168.252.128

  #rabbit消息队列
  rabbitmq:
    host: 192.168.252.128
    port: 5672
    virtual-host: /
    #开启手动确认消息处理
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 16000
  #  1-配置全局的逻辑删除规则
  #  2-配置逻辑删除的组件Bean---（MybatisPlus3.0以上无需配置）V
  #  3-给Bean加上逻辑删除注解@TableLogic
  global-config:
    db-config:    ##配置逻辑删除
      id-type: auto
      logic-delete-value: 1   #逻辑删除1为删除
      logic-not-delete-value: 0   #逻辑删除0为不删除

#线程池参数设定
foodmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

logging:
  level:
    com.atghy.foodmall: info